#!/bin/sh
set_gpio()
{
    if [ ! -d "/sys/class/gpio/GPIO$1" ]; then
        echo $1 > /sys/class/gpio/export
        echo out > /sys/class/gpio/GPIO$1/direction
    fi
    echo $2 > /sys/class/gpio/GPIO$1/value
}
cd /lib/modules/4.9.129/fullhan
insmod vmm.ko mmz=anonymous,0,0xa5000000,63M anony=1
set_gpio 13 0
insmod xbus_rpc.ko fn=/lib/firmware/rtthread_arc_FH885xV200.bin fa=0xbff80000
set_gpio 13 1
insmod media_process.ko
insmod isp.ko
insmod vpu.ko vpu_mode=buf_0_1,buf_1_2
insmod enc.ko
insmod jpeg.ko
insmod bgm.ko
echo adv_vpu > /proc/driver/media_process
echo cap_0_2880_1620 > /proc/driver/vpu
echo buf_0_1 > /proc/driver/vpu
